org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
forge_version=47.2.30
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=itembordersstoragecompat
mod_name=Item Borders: Storage Compat
mod_license=ARR
mod_version=1.1.0
mod_group_id=org.example.itembordersstoragecompat
mod_authors=QLN
mod_description=Item Borders: Storage Compat is a client-side compatibility mod that brings Item Borders' rarity-based borders to custom storage interfaces. It currently supports Refined Storage and Tom's Simple Storage Mod, respects your existing Item Borders settings, and does not need to be installed on the server.
